server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://101.34.207.75:3306/project_work?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml